//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F4ToPokeys.Translations {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F4ToPokeys.Translations.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a digital output.
        /// </summary>
        public static string AddDigitalOutputButton {
            get {
                return ResourceManager.GetString("AddDigitalOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a matrix LED output.
        /// </summary>
        public static string AddMatrixLedOutputButton {
            get {
                return ResourceManager.GetString("AddMatrixLedOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a PoExtBus output.
        /// </summary>
        public static string AddPoExtBusOutputButton {
            get {
                return ResourceManager.GetString("AddPoExtBusOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a PoKeys.
        /// </summary>
        public static string AddPoKeysButton {
            get {
                return ResourceManager.GetString("AddPoKeysButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Pololu Maestro.
        /// </summary>
        public static string AddPololuMaestroButton {
            get {
                return ResourceManager.GetString("AddPololuMaestroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a servo.
        /// </summary>
        public static string AddServoButton {
            get {
                return ResourceManager.GetString("AddServoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a point.
        /// </summary>
        public static string AddServoPointButton {
            get {
                return ResourceManager.GetString("AddServoPointButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a 7 segment display.
        /// </summary>
        public static string AddSevenSegmentDisplayButton {
            get {
                return ResourceManager.GetString("AddSevenSegmentDisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à F4ToPokeys started.
        /// </summary>
        public static string ApplicationStartedBalloonTip {
            get {
                return ResourceManager.GetString("ApplicationStartedBalloonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à F4ToPokeys.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration load error.
        /// </summary>
        public static string ConfigLoadErrorCaption {
            get {
                return ResourceManager.GetString("ConfigLoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration save error.
        /// </summary>
        public static string ConfigSaveErrorCaption {
            get {
                return ResourceManager.GetString("ConfigSaveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove a digit.
        /// </summary>
        public static string DecrementTotalSizeButton {
            get {
                return ResourceManager.GetString("DecrementTotalSizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digital output.
        /// </summary>
        public static string DigitalOutputConfigCaption {
            get {
                return ResourceManager.GetString("DigitalOutputConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This pin is not a digital output.
        /// </summary>
        public static string DigitalOutputErrorBadIOType {
            get {
                return ResourceManager.GetString("DigitalOutputErrorBadIOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin IO type read error.
        /// </summary>
        public static string DigitalOutputErrorGetIOType {
            get {
                return ResourceManager.GetString("DigitalOutputErrorGetIOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digital output write error.
        /// </summary>
        public static string DigitalOutputErrorWrite {
            get {
                return ResourceManager.GetString("DigitalOutputErrorWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        public static string FalconLightConsumerConfigOffButton {
            get {
                return ResourceManager.GetString("FalconLightConsumerConfigOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        public static string FalconLightConsumerConfigOnButton {
            get {
                return ResourceManager.GetString("FalconLightConsumerConfigOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Falcon data sampling interval:.
        /// </summary>
        public static string FalconSamplingInterval {
            get {
                return ResourceManager.GetString("FalconSamplingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à milliseconds.
        /// </summary>
        public static string FalconSamplingUnit {
            get {
                return ResourceManager.GetString("FalconSamplingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum digit number after decimal point.
        /// </summary>
        public static string FractionalPartSizeCaption {
            get {
                return ResourceManager.GetString("FractionalPartSizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a digit.
        /// </summary>
        public static string IncrementTotalSizeButton {
            get {
                return ResourceManager.GetString("IncrementTotalSizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum digit number before decimal point.
        /// </summary>
        public static string IntegralPartMinSizeCaption {
            get {
                return ResourceManager.GetString("IntegralPartMinSizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This matrix LED display is not enabled.
        /// </summary>
        public static string MatrixLedErrorNotEnabled {
            get {
                return ResourceManager.GetString("MatrixLedErrorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matrix LED display write error.
        /// </summary>
        public static string MatrixLedErrorWrite {
            get {
                return ResourceManager.GetString("MatrixLedErrorWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matrix LED output.
        /// </summary>
        public static string MatrixLedOutputConfigCaption {
            get {
                return ResourceManager.GetString("MatrixLedOutputConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column.
        /// </summary>
        public static string MatrixLedOutputConfigColumn {
            get {
                return ResourceManager.GetString("MatrixLedOutputConfigColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Row.
        /// </summary>
        public static string MatrixLedOutputConfigRow {
            get {
                return ResourceManager.GetString("MatrixLedOutputConfigRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This matrix LED output ({0}, {1}) is not enabled.
        /// </summary>
        public static string MatrixLedPixelErrorNotEnabled {
            get {
                return ResourceManager.GetString("MatrixLedPixelErrorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure.
        /// </summary>
        public static string MenuItemConfigure {
            get {
                return ResourceManager.GetString("MenuItemConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string MenuItemQuit {
            get {
                return ResourceManager.GetString("MenuItemQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed size.
        /// </summary>
        public static string PadFractionalPartWithZeroCaption {
            get {
                return ResourceManager.GetString("PadFractionalPartWithZeroCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The PoExtBus is not enabled.
        /// </summary>
        public static string PoExtBusErrorNotEnabled {
            get {
                return ResourceManager.GetString("PoExtBusErrorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PoExtBus write error.
        /// </summary>
        public static string PoExtBusErrorWrite {
            get {
                return ResourceManager.GetString("PoExtBusErrorWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PoExtBus output.
        /// </summary>
        public static string PoExtBusOutputConfigCaption {
            get {
                return ResourceManager.GetString("PoExtBusOutputConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device.
        /// </summary>
        public static string PoExtBusOutputConfigDevice {
            get {
                return ResourceManager.GetString("PoExtBusOutputConfigDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PoKeys.
        /// </summary>
        public static string PoKeysConfigCaption {
            get {
                return ResourceManager.GetString("PoKeysConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PoKeys connection error.
        /// </summary>
        public static string PokeysConnectError {
            get {
                return ResourceManager.GetString("PokeysConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not found.
        /// </summary>
        public static string PokeysNotFoundError {
            get {
                return ResourceManager.GetString("PokeysNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pololu Maestro.
        /// </summary>
        public static string PololuMaestroConfigCaption {
            get {
                return ResourceManager.GetString("PololuMaestroConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not found.
        /// </summary>
        public static string PololuMaestroNotFoundError {
            get {
                return ResourceManager.GetString("PololuMaestroNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove digital output.
        /// </summary>
        public static string RemoveDigitalOutputCaption {
            get {
                return ResourceManager.GetString("RemoveDigitalOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove digital output {0} ?.
        /// </summary>
        public static string RemoveDigitalOutputText {
            get {
                return ResourceManager.GetString("RemoveDigitalOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove matrix LED output.
        /// </summary>
        public static string RemoveMatrixLedOutputCaption {
            get {
                return ResourceManager.GetString("RemoveMatrixLedOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove matrix LED output ({1}, {2}) of {0} ?.
        /// </summary>
        public static string RemoveMatrixLedOutputText {
            get {
                return ResourceManager.GetString("RemoveMatrixLedOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove PoExtBus output.
        /// </summary>
        public static string RemovePoExtBusOutputCaption {
            get {
                return ResourceManager.GetString("RemovePoExtBusOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove PoExtBus output {1} of device {0} ?.
        /// </summary>
        public static string RemovePoExtBusOutputText {
            get {
                return ResourceManager.GetString("RemovePoExtBusOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove PoKeys.
        /// </summary>
        public static string RemovePoKeysCaption {
            get {
                return ResourceManager.GetString("RemovePoKeysCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove PoKeys {0} ?.
        /// </summary>
        public static string RemovePoKeysText {
            get {
                return ResourceManager.GetString("RemovePoKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Pololu Maestro.
        /// </summary>
        public static string RemovePololuMaestroCaption {
            get {
                return ResourceManager.GetString("RemovePololuMaestroCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Pololu Maestro {0} ?.
        /// </summary>
        public static string RemovePololuMaestroText {
            get {
                return ResourceManager.GetString("RemovePololuMaestroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Servo.
        /// </summary>
        public static string RemoveServoCaption {
            get {
                return ResourceManager.GetString("RemoveServoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Servo {0} ?.
        /// </summary>
        public static string RemoveServoText {
            get {
                return ResourceManager.GetString("RemoveServoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove 7 segment display.
        /// </summary>
        public static string RemoveSevenSegmentDisplayCaption {
            get {
                return ResourceManager.GetString("RemoveSevenSegmentDisplayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove 7 segment display {0} ?.
        /// </summary>
        public static string RemoveSevenSegmentDisplayText {
            get {
                return ResourceManager.GetString("RemoveSevenSegmentDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servo.
        /// </summary>
        public static string ServoConfigCaption {
            get {
                return ResourceManager.GetString("ServoConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Falcon value.
        /// </summary>
        public static string ServoPointFalconValue {
            get {
                return ResourceManager.GetString("ServoPointFalconValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Servo value.
        /// </summary>
        public static string ServoPointServoValue {
            get {
                return ResourceManager.GetString("ServoPointServoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digit matrix LED column index.
        /// </summary>
        public static string SevenSegmentDigitColumnCaption {
            get {
                return ResourceManager.GetString("SevenSegmentDigitColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digit matrix LED row index.
        /// </summary>
        public static string SevenSegmentDigitRowCaption {
            get {
                return ResourceManager.GetString("SevenSegmentDigitRowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7 segment display.
        /// </summary>
        public static string SevenSegmentDisplayConfigCaption {
            get {
                return ResourceManager.GetString("SevenSegmentDisplayConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swap rows and columns of the matrix LED.
        /// </summary>
        public static string SevenSegmentInvertRowColumnOption {
            get {
                return ResourceManager.GetString("SevenSegmentInvertRowColumnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Segment matrix LED column index :.
        /// </summary>
        public static string SevenSegmentSegmentColumnCaption {
            get {
                return ResourceManager.GetString("SevenSegmentSegmentColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Segment matrix LED row index :.
        /// </summary>
        public static string SevenSegmentSegmentRowCaption {
            get {
                return ResourceManager.GetString("SevenSegmentSegmentRowCaption", resourceCulture);
            }
        }
    }
}
