//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F4ToPokeys.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F4ToPokeys.Translations.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a digital output.
        /// </summary>
        public static string AddDigitalOutputButton {
            get {
                return ResourceManager.GetString("AddDigitalOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a matrix LED output.
        /// </summary>
        public static string AddMatrixLedOutputButton {
            get {
                return ResourceManager.GetString("AddMatrixLedOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PoExtBus output.
        /// </summary>
        public static string AddPoExtBusOutputButton {
            get {
                return ResourceManager.GetString("AddPoExtBusOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a PoKeys.
        /// </summary>
        public static string AddPoKeysButton {
            get {
                return ResourceManager.GetString("AddPoKeysButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Pololu Maestro.
        /// </summary>
        public static string AddPololuMaestroButton {
            get {
                return ResourceManager.GetString("AddPololuMaestroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a servo.
        /// </summary>
        public static string AddServoButton {
            get {
                return ResourceManager.GetString("AddServoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a point.
        /// </summary>
        public static string AddServoPointButton {
            get {
                return ResourceManager.GetString("AddServoPointButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a 7 segment display.
        /// </summary>
        public static string AddSevenSegmentDisplayButton {
            get {
                return ResourceManager.GetString("AddSevenSegmentDisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4ToPokeys started.
        /// </summary>
        public static string ApplicationStartedBalloonTip {
            get {
                return ResourceManager.GetString("ApplicationStartedBalloonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4ToPokeys.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration load error.
        /// </summary>
        public static string ConfigLoadErrorCaption {
            get {
                return ResourceManager.GetString("ConfigLoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration save error.
        /// </summary>
        public static string ConfigSaveErrorCaption {
            get {
                return ResourceManager.GetString("ConfigSaveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a digit.
        /// </summary>
        public static string DecrementTotalSizeButton {
            get {
                return ResourceManager.GetString("DecrementTotalSizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital output.
        /// </summary>
        public static string DigitalOutputConfigCaption {
            get {
                return ResourceManager.GetString("DigitalOutputConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pin is not a digital output.
        /// </summary>
        public static string DigitalOutputErrorBadIOType {
            get {
                return ResourceManager.GetString("DigitalOutputErrorBadIOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin IO type read error.
        /// </summary>
        public static string DigitalOutputErrorGetIOType {
            get {
                return ResourceManager.GetString("DigitalOutputErrorGetIOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital output write error.
        /// </summary>
        public static string DigitalOutputErrorWrite {
            get {
                return ResourceManager.GetString("DigitalOutputErrorWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable BMS Shared Memory Output.
        /// </summary>
        public static string DisableMemorySlotOutputButton {
            get {
                return ResourceManager.GetString("DisableMemorySlotOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable BMS Shared Memory Output.
        /// </summary>
        public static string EnableMemorySlotOutputButton {
            get {
                return ResourceManager.GetString("EnableMemorySlotOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FalconLightConsumerConfigOffButton {
            get {
                return ResourceManager.GetString("FalconLightConsumerConfigOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FalconLightConsumerConfigOnButton {
            get {
                return ResourceManager.GetString("FalconLightConsumerConfigOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falcon data sampling interval:.
        /// </summary>
        public static string FalconSamplingInterval {
            get {
                return ResourceManager.GetString("FalconSamplingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        public static string FalconSamplingUnit {
            get {
                return ResourceManager.GetString("FalconSamplingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum digit number after decimal point.
        /// </summary>
        public static string FractionalPartSizeCaption {
            get {
                return ResourceManager.GetString("FractionalPartSizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a digit.
        /// </summary>
        public static string IncrementTotalSizeButton {
            get {
                return ResourceManager.GetString("IncrementTotalSizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum digit number before decimal point.
        /// </summary>
        public static string IntegralPartMinSizeCaption {
            get {
                return ResourceManager.GetString("IntegralPartMinSizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This matrix LED display is not enabled.
        /// </summary>
        public static string MatrixLedErrorNotEnabled {
            get {
                return ResourceManager.GetString("MatrixLedErrorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix LED display write error.
        /// </summary>
        public static string MatrixLedErrorWrite {
            get {
                return ResourceManager.GetString("MatrixLedErrorWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix LED output.
        /// </summary>
        public static string MatrixLedOutputConfigCaption {
            get {
                return ResourceManager.GetString("MatrixLedOutputConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string MatrixLedOutputConfigColumn {
            get {
                return ResourceManager.GetString("MatrixLedOutputConfigColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string MatrixLedOutputConfigRow {
            get {
                return ResourceManager.GetString("MatrixLedOutputConfigRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This matrix LED output ({0}, {1}) is not enabled.
        /// </summary>
        public static string MatrixLedPixelErrorNotEnabled {
            get {
                return ResourceManager.GetString("MatrixLedPixelErrorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format :.
        /// </summary>
        public static string MemorySlotOutputFormatCaption {
            get {
                return ResourceManager.GetString("MemorySlotOutputFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits :.
        /// </summary>
        public static string MemorySlotOutputShiftBitsCaption {
            get {
                return ResourceManager.GetString("MemorySlotOutputShiftBitsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoKeys Memory Slot :.
        /// </summary>
        public static string MemorySlotOutputSlotIdCaption {
            get {
                return ResourceManager.GetString("MemorySlotOutputSlotIdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value :.
        /// </summary>
        public static string MemorySlotOutputValueCaption {
            get {
                return ResourceManager.GetString("MemorySlotOutputValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string MenuItemConfigure {
            get {
                return ResourceManager.GetString("MenuItemConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MenuItemQuit {
            get {
                return ResourceManager.GetString("MenuItemQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed size.
        /// </summary>
        public static string PadFractionalPartWithZeroCaption {
            get {
                return ResourceManager.GetString("PadFractionalPartWithZeroCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PoExtBus is not enabled.
        /// </summary>
        public static string PoExtBusErrorNotEnabled {
            get {
                return ResourceManager.GetString("PoExtBusErrorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoExtBus write error.
        /// </summary>
        public static string PoExtBusErrorWrite {
            get {
                return ResourceManager.GetString("PoExtBusErrorWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoExtBus output.
        /// </summary>
        public static string PoExtBusOutputConfigCaption {
            get {
                return ResourceManager.GetString("PoExtBusOutputConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string PoExtBusOutputConfigDevice {
            get {
                return ResourceManager.GetString("PoExtBusOutputConfigDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoKeys.
        /// </summary>
        public static string PoKeysConfigCaption {
            get {
                return ResourceManager.GetString("PoKeysConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoKeys connection error.
        /// </summary>
        public static string PokeysConnectError {
            get {
                return ResourceManager.GetString("PokeysConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string PokeysNotFoundError {
            get {
                return ResourceManager.GetString("PokeysNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pololu Maestro.
        /// </summary>
        public static string PololuMaestroConfigCaption {
            get {
                return ResourceManager.GetString("PololuMaestroConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string PololuMaestroNotFoundError {
            get {
                return ResourceManager.GetString("PololuMaestroNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove digital output.
        /// </summary>
        public static string RemoveDigitalOutputCaption {
            get {
                return ResourceManager.GetString("RemoveDigitalOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove digital output {0} ?.
        /// </summary>
        public static string RemoveDigitalOutputText {
            get {
                return ResourceManager.GetString("RemoveDigitalOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove matrix LED output.
        /// </summary>
        public static string RemoveMatrixLedOutputCaption {
            get {
                return ResourceManager.GetString("RemoveMatrixLedOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove matrix LED output ({1}, {2}) of {0} ?.
        /// </summary>
        public static string RemoveMatrixLedOutputText {
            get {
                return ResourceManager.GetString("RemoveMatrixLedOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PoExtBus output.
        /// </summary>
        public static string RemovePoExtBusOutputCaption {
            get {
                return ResourceManager.GetString("RemovePoExtBusOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PoExtBus output {1} of device {0} ?.
        /// </summary>
        public static string RemovePoExtBusOutputText {
            get {
                return ResourceManager.GetString("RemovePoExtBusOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PoKeys.
        /// </summary>
        public static string RemovePoKeysCaption {
            get {
                return ResourceManager.GetString("RemovePoKeysCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PoKeys {0} ?.
        /// </summary>
        public static string RemovePoKeysText {
            get {
                return ResourceManager.GetString("RemovePoKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Pololu Maestro.
        /// </summary>
        public static string RemovePololuMaestroCaption {
            get {
                return ResourceManager.GetString("RemovePololuMaestroCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Pololu Maestro {0} ?.
        /// </summary>
        public static string RemovePololuMaestroText {
            get {
                return ResourceManager.GetString("RemovePololuMaestroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Servo.
        /// </summary>
        public static string RemoveServoCaption {
            get {
                return ResourceManager.GetString("RemoveServoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Servo {0} ?.
        /// </summary>
        public static string RemoveServoText {
            get {
                return ResourceManager.GetString("RemoveServoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove 7 segment display.
        /// </summary>
        public static string RemoveSevenSegmentDisplayCaption {
            get {
                return ResourceManager.GetString("RemoveSevenSegmentDisplayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove 7 segment display {0} ?.
        /// </summary>
        public static string RemoveSevenSegmentDisplayText {
            get {
                return ResourceManager.GetString("RemoveSevenSegmentDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo.
        /// </summary>
        public static string ServoConfigCaption {
            get {
                return ResourceManager.GetString("ServoConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falcon value.
        /// </summary>
        public static string ServoPointFalconValue {
            get {
                return ResourceManager.GetString("ServoPointFalconValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo value.
        /// </summary>
        public static string ServoPointServoValue {
            get {
                return ResourceManager.GetString("ServoPointServoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit matrix LED column index.
        /// </summary>
        public static string SevenSegmentDigitColumnCaption {
            get {
                return ResourceManager.GetString("SevenSegmentDigitColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit matrix LED row index.
        /// </summary>
        public static string SevenSegmentDigitRowCaption {
            get {
                return ResourceManager.GetString("SevenSegmentDigitRowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 segment display.
        /// </summary>
        public static string SevenSegmentDisplayConfigCaption {
            get {
                return ResourceManager.GetString("SevenSegmentDisplayConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap rows and columns of the matrix LED.
        /// </summary>
        public static string SevenSegmentInvertRowColumnOption {
            get {
                return ResourceManager.GetString("SevenSegmentInvertRowColumnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment matrix LED column index :.
        /// </summary>
        public static string SevenSegmentSegmentColumnCaption {
            get {
                return ResourceManager.GetString("SevenSegmentSegmentColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment matrix LED row index :.
        /// </summary>
        public static string SevenSegmentSegmentRowCaption {
            get {
                return ResourceManager.GetString("SevenSegmentSegmentRowCaption", resourceCulture);
            }
        }
    }
}
